# Generated by Django 2.0.4 on 2018-08-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellouser', '0002_auto_20180813_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='address2',
            new_name='address_optional',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='shipping_address2',
            new_name='shipping_address_optional',
        ),
    ]
