# Generated by Django 2.0.4 on 2018-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellouser', '0003_auto_20180813_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес отправки'),
        ),
    ]
