# Generated by Django 2.0.4 on 2018-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hellouser', '0004_myuser_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
    ]
